### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MahmoudEllafi** [ken0225/RIS-Distance-Dependent-Rician-Channels#2]
Please i have some questions regarding the code

**Comment by ken0225** [comment]
No problem, please send an email to ke.wang@mpu.edu.mo, then I will sent it to you via email.

Please note that the code is licensed under the GPLv2 license and is delivered as it is. The authors encourage you to reuse the code in your research, but we cannot give any support.  As soon as you edit the code, you are on your own. 

Besides, please CITE this work if you use the code.

Best regards

Ke(Ken)Wang
